stages:
  prepare:
    cmd: python -m src.data_proc.prepare
    deps:
      - src/data_proc/prepare.py
      - ${prepare.metadata_path}
      - ${prepare.image_dir_part1}
      - ${prepare.image_dir_part2}
      - ${prepare.test_images_dir}
      - ${prepare.test_metadata_path}
    params:
      - prepare
    outs:
      - ${prepare.processed_dir}/${prepare.processed_train_csv}
      - ${prepare.processed_dir}/${prepare.processed_val_csv}
      - ${prepare.processed_dir}/${prepare.processed_test_csv}
    metrics:
      - ${prepare.prepare_summary_report}:
          cache: false
      - ${prepare.baseline_stats_report}:
          cache: false

  train:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - src/models/model.py
      - src/utils/mlflow_utils.py
      - src/utils/metrics.py
      - src/utils/reproducibility.py  
      - src/utils/logger.py
      - ${prepare.processed_dir}/${prepare.processed_train_csv}
      - ${prepare.processed_dir}/${prepare.processed_val_csv}
      - ${prepare.baseline_stats_report}
    params:
      - train
      - prepare
    outs:
      - ${evaluate.model_path}
    metrics:
      - ${train.train_history_path}:
          cache: false
      - ${train.mlflow_runid_path}:
          cache: false

  evaluate:
    cmd: python -m src.models.inference
    deps:
      - src/models/inference.py
      - src/models/model.py                
      - src/models/train.py                
      - src/utils/mlflow_utils.py          
      - src/utils/metrics.py               
      - src/utils/reproducibility.py       
      - src/utils/logger.py                
      - ${evaluate.model_path}
      - ${train.mlflow_runid_path}
      - ${prepare.processed_dir}/${prepare.processed_test_csv}
    params:
      - train
      - evaluate
    metrics:
      - ${evaluate.eval_metrics_path}:
          cache: false
    plots:
      - ${evaluate.confusion_mat_path}
    outs:
      - ${evaluate.gradcam_path}:
          cache: false
